name: Build and Push to ECR

on:
  push:
    branches: [main]
    paths:
      - 'auth-service/**'
      - 'flag-service/**'
      - 'targeting-service/**'
      - 'evaluation-service/**'
      - 'analytics-service/**'
  workflow_dispatch:  # permite rodar manualmente pelo GitHub também

env:
  AWS_REGION: us-east-1
  ECR_PREFIX: fiap

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth-service
          - flag-service
          - targeting-service
          - evaluation-service
          - analytics-service

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag e push da imagem
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO_NAME: ${{ env.ECR_PREFIX }}/${{ matrix.service }}
        run: |
          docker build -t $ECR_REGISTRY/$REPO_NAME:latest ./${{ matrix.service }}
          docker build -t $ECR_REGISTRY/$REPO_NAME:${{ github.sha }} ./${{ matrix.service }}
          docker push $ECR_REGISTRY/$REPO_NAME:latest
          docker push $ECR_REGISTRY/$REPO_NAME:${{ github.sha }}
